server:
  port: 8080

spring:
  cache:
    type: redis
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:redis}
      port: ${SPRING_DATA_REDIS_PORT:6379}
  application:
    name: mortgage
  datasource:
    url: jdbc:postgresql://db:5432/mydb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
