server:
  port: 8080

spring:
  cache:
    type: redis
  data:
   redis:
     host: ${SPRING_DATA_REDIS_HOST:redis}
     port: ${SPRING_DATA_REDIS_PORT:6379}
  application:
    name: mortgage
  datasource:
    url: jdbc:h2:mem:mortgage-db
    driverClassName: org.h2.Driver
    username: test
    password: test
  h2:
    console:
      enabled: true
      path: /h2-console